Derinsis.B2B/Controllers/SupplierController.cs
namespace DerinSIS.B2B.Controllers
{
    using System.Web.Mvc;
    using Infrastructure.Auth;
    using Models;
    using System;
    using ViewModels;
    using System.Linq;
    using Helpers;
    using Helpers.Html;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Web.Script.Serialization;
    using Helpers;
    using System.Net;
    using System.Data;
    using System.Data.SqlClient;
    using System.IO;
    using System.Web.UI;
    using System.Text;
    using iTextSharp.text.html.simpleparser;
    using iTextSharp.text.pdf;
    using iTextSharp.text;
    using System.Web;
    using System.Drawing;

    [B2BAuthorize(AccountType.Supplier, Privilege.SIPARIS)]
    public class SupplierController : BaseController
    {
        public SupplierController(DbEntities db) : base(db)
        {
        }

        #region Product List

        public ActionResult Index(string q, int? categoryId, string brandId, int? producerId, int? page, string kmp, string price, string priceLabel, string ynUrn, string stogaYeniGirenUrn, string oneCikanUrn, string ordercondition)
        {
            var model = new ProductListModel();

            page = page ?? 1;
            var pageLength = 28;

            short _brandID = -1;
            var _brandGrupID = 0;
            if (brandId != null && brandId != "")
            {
                if (brandId.IndexOf('-') > -1)
                {
                    _brandID = Convert.ToInt16(brandId.Split('-')[0]);
                    _brandGrupID = Convert.ToInt32(brandId.Split('-')[1]);
                }
                else
                {
                    _brandID = Convert.ToInt16(brandId);
                }
            }

            if (!String.IsNullOrWhiteSpace(ordercondition))
                model.siralama = ordercondition;

            var yeniUrunListesi = Db.urnYeniler_vw.Select(x => x.stkID).ToList();
            if (yeniUrunListesi.Count() == 0)
            {
                model.UrunYeniler = -1;
            }
            else
            {
                model.UrunYeniler = (ynUrn == "on") ? 1 : 0;
            }

            var stogaYeniGirenUrnListesi = Db.urnStogaYeniGirenler_vw.Select(x => x.stkID).ToList();
            if (stogaYeniGirenUrnListesi.Count() == 0)
            {
                model.UrunStogaYeniGirenler = -1;
            }
            else
            {
                model.UrunStogaYeniGirenler = (stogaYeniGirenUrn == "on") ? 1 : 0;
            }

            var OneCikanUrnListesi = Db.urnOneCikanlar_vw.Select(x => x.stkID).ToList();
            if (OneCikanUrnListesi.Count() == 0)
            {
                model.UrunOneCikanlar = -1;
            }
            else
            {
                model.UrunOneCikanlar = (oneCikanUrn == "on") ? 1 : 0;
            }

            model.OzelFiyat = kmp == "on" ? true : false;


            string sorguEkKosul = " where 1=1 ";
            if (!String.IsNullOrWhiteSpace(q))
            {
                model.Sorgu = q;
                if (isNumeric(q) && q.Length >= 8)
                {
                    sorguEkKosul += " and alis.stkID in (select (case when urnBrkdAltStkId>0 then urnBrkdAltStkId else urnBrkdStkID end) as urnBrkdStkID from urnBrkd where urnBarkod like '%" + q + "%') ";
                }
                else
                {
                    var qstr = q.Split(' ').Select(x => x.ToLower()).ToArray();
                    if (qstr.Count() > 0)
                    {
                        sorguEkKosul += " and (alis.stkKod like '%" + q + "%' or alis.mrkAd like '%" + q + "%' or ( ";
                        for (int i = 0; i < qstr.Count(); i++)
                        {
                            if (i + 1 == qstr.Count())
                            {
                                sorguEkKosul += " alis.stkAd like '%" + qstr[i] + "%' ";
                            }
                            else
                            {
                                sorguEkKosul += " alis.stkAd like '%" + qstr[i] + "%' and ";
                            }
                        }
                        sorguEkKosul += " )) ";
                    }
                }
            }


            /* Kategori Koşul Filter */
            if (categoryId != null)
            {
                string sorgu = @" select * from b2b.fn_urnAlisKategori_Vw(" + CurrentAccount.frm.frmID + ") where kID=" + categoryId + " ";
                var kategori = Db.Database.SqlQuery<Categories>(sorgu).ToList().Single();

                model.KategoriIdFiltresi = kategori.kID;
                model.KategoriFiltreEtiketi = kategori.kAd;

                sorguEkKosul += " and urnKtgrID=" + kategori.k0 + " ";

                if (kategori.k1 != 0)
                {
                    sorguEkKosul += " and urnKtgrID1=" + kategori.k1 + " ";
                }

                if (kategori.k2 != 0)
                {
                    sorguEkKosul += " and urnKtgrID2=" + kategori.k2 + " ";
                }

                if (kategori.k3 != 0)
                {
                    sorguEkKosul += " and urnKtgrID3=" + kategori.k3 + " ";
                }
            }


            /* Üretici Koşul Filter */
            if (producerId != null)
            {
                var uretici = Db.urnMrkUrt.Single(x => x.urtID == producerId);
                model.UreticiIdFiltresi = uretici.urtID;
                model.UreticiFiltreEtiketi = uretici.urtAd;

                sorguEkKosul += " and urtID=" + uretici.urtID + " ";
            }

            /* Marka Koşul Filter */
            if (_brandID != -1)
            {
                if (_brandGrupID == 1)
                {
                    var markaGrup = Db.urnMrkGrp.Single(x => x.urnMrkGrpID == _brandID);
                    model.MarkaIdFiltresi = brandId;
                    model.MarkaFiltreEtiketi = markaGrup.urnMrkGrpAd;

                    sorguEkKosul += " and urnMrkGrpID=" + markaGrup.urnMrkGrpID + " ";
                }
                else
                {
                    var marka = Db.urnMrk.Single(x => x.mrkID == _brandID);
                    model.MarkaIdFiltresi = brandId;
                    model.MarkaFiltreEtiketi = marka.mrkAd;

                    sorguEkKosul += " and urnMrkID=" + marka.mrkID + " ";
                }
            }

            if (price != null && price != "")
            {
                var esik = price.Split('-');
                int min = int.Parse(esik[0]);
                int max = esik[1] != "" ? int.Parse(esik[1]) : 99999999;
                model.FiyatFiltresi = price;
                model.FiyatFiltreEtiketi = priceLabel;

                sorguEkKosul += " and ((case when odemeKur>0 then odemeKur*fiyatA else fiyatA end)>=" + min + " and (case when odemeKur>0 then odemeKur*fiyatA else fiyatA end)<=" + max + ") ";
            }

            if (model.UrunYeniler > 0)
            {
                sorguEkKosul += " and alis.stkID in (select stkID from b2b.urnYeniler_vw) ";
            }

            if (model.UrunStogaYeniGirenler > 0)
            {
                sorguEkKosul += " and alis.stkID in (select stkID from b2b.urnStogaYeniGirenler_vw) ";
            }

            if (model.UrunOneCikanlar > 0)
            {
                sorguEkKosul += " and alis.stkID in (select stkID from b2b.urnOneCikanlar_vw) ";
            }

            string orderKosul = " order by (case when urnGrpID = 0 then rtb else 0 end),(case when urnGrpID = 0 then stkAd else grpAd end),stkID ";

            var stkGosterimiVar = StkGosterimiVar;
            var brutFiyatGosterimiVar = BrutFiyatGostermiVar;
            model.StokGosterimiVar = stkGosterimiVar;

            if (!String.IsNullOrWhiteSpace(ordercondition))
            {
                switch (ordercondition)
                {
                    case "0-0":
                        orderKosul = " order by (case when urnGrpID = 0 then stkKod else '' end),(case when urnGrpID = 0 then stkAd else grpAd end),stkID ";
                        break;
                    case "0-1":
                        orderKosul = " order by (case when urnGrpID = 0 then stkKod else '' end) desc,(case when urnGrpID = 0 then stkAd else grpAd end),stkID ";
                        break;
                    case "1-0":
                        orderKosul = " order by (case when urnGrpID = 0 then stkAd else grpAd end),stkID ";
                        break;
                    case "1-1":
                        orderKosul = " order by (case when urnGrpID = 0 then stkAd else grpAd end) desc,stkID ";
                        break;
                    case "2-0":
                        orderKosul = " order by (case when urnGrpID = 0 then barkod else '' end),(case when urnGrpID = 0 then stkAd else grpAd end),stkID ";
                        break;
                    case "2-1":
                        orderKosul = " order by (case when urnGrpID = 0 then barkod else '' end) desc,(case when urnGrpID = 0 then stkAd else grpAd end),stkID ";
                        break;
                    case "3-0":
                        orderKosul = " order by (case when urnGrpID = 0 then urnKoli else 1 end),(case when urnGrpID = 0 then stkAd else grpAd end),stkID ";
                        break;
                    case "3-1":
                        orderKosul = " order by (case when urnGrpID = 0 then urnKoli else 1 end) desc,(case when urnGrpID = 0 then stkAd else grpAd end),stkID ";
                        break;
                    case "4-0":
                        orderKosul = " order by (case when urnGrpID = 0 then urnKutu else -1 end),(case when urnGrpID = 0 then stkAd else grpAd end),stkID ";
                        break;
                    case "4-1":
                        orderKosul = " order by (case when urnGrpID = 0 then urnKutu else -1 end) desc,(case when urnGrpID = 0 then stkAd else grpAd end),stkID ";

Derinsis.B2B/Views/Supplier/PrivateProductPriceListReport.cshtml
@using DerinSIS.B2B.ViewModels
@model PrivateProductPriceListReportModel
@{
    ViewBag.Title = "Özel Fiyat Ürün Liste Raporu";
}


<form method="GET" class="pager-form">
    <div class="clearfix product-search-elements" style="margin-bottom: 10px">
        <table>
            <tr>
                <td>
                    <input type="text" id="q" name="q" class="search-box" value="@Model.Sorgu" placeholder="Ürün Adı İçinde Ara" style="margin-bottom:0px" />
                </td>
                <td>
                    <button type="submit" class="btn" data-loading-text="Ara">Ara</button>
                </td>
            </tr>
        </table>
    </div>
    @{ Html.RenderPartial("DocumentSingleDateFilter", Model.DateFilter); }
    <div class="clearfix">
        @if (!Model.PrivateProductPriceListReports.Any())
        {
            <div class="alert alert-error">
                <h4 class="alert-heading">Kayıt Bulunamadı!</h4>
                Lütfen arama koşullarını değiştirip tekrar deneyin.
            </div>
        }
        else
        {
            <div id="product-list-summary" class="well">
                <div class="clearfix">
                    <div style="float: left; width: 80%; line-height: 30px;">
                        @{  var topSay = Model.PrivateProductPriceListReports.FirstOrDefault().topSay;
                            var topPages = Model.PrivateProductPriceListReports.FirstOrDefault().topSay / Model.PageLength;
                            var topKalan = Model.PrivateProductPriceListReports.FirstOrDefault().topSay % Model.PageLength;
                            if (topKalan > 0)
                            {
                                topPages = topPages + 1;
                            }
                        }
                        @if (Model.Page == 1)
                        {
                            <em>Toplam @topSay sonuç bulundu</em>
                        }
                        else
                        {
                            <em>Sayfa @Model.Page / @topPages sonuç</em>
                        }
                    </div>
                    <div>
                        <a href="javascript:myFunction()">
                            <img width="32" height="32" align="right" src="/Assets/theme/img/Excel-icon.png" id="excel" alt="Export to Excel" title="Export to Excel" />
                        </a>
                    </div>
                </div>
            </div>

            <div class="table-responsive">
                <table id="MyProductTable" class="table table-striped">
                    <thead>
                        <tr>
                            <th style="min-width:70px">Ürün Kod</th>
                            <th style="min-width:90px">Dağıtıcı Kod</th>
                            <th style="min-width:70px">Barkod</th>
                            <th style="min-width:500px">Ürün Ad</th>
                            <th style="text-align:right;min-width:80px">Net Alış</th>
                            <th style="text-align:right;min-width:80px">Kdvli Alış</th>
                            <th style="text-align:right;min-width:80px">Satış</th>
                            <th style="text-align:right;min-width:80px">Kdvli Satış</th>
                            <th style="min-width:80px">Son Tarih</th>
                            <th style="min-width:750px">Kategori</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model.PrivateProductPriceListReports)
                        {
                            <tr>
                                <td>@product.stkKod</td>
                                <td>@product.dagiticiKod</td>
                                <td>@product.barkod</td>
                                <td data-toggle="tooltip" title="@product.stkAd">@product.stkAd.ToString().TruncateAtWord(45)</td>
                                <td class="right-aligned no-wrap">@product.netAlis.ToMoneyFormat()</td>
                                <td class="right-aligned no-wrap">@product.kdvliAlis.ToMoneyFormat()</td>
                                <td class="right-aligned no-wrap">@product.satis.ToMoneyFormat()</td>
                                <td class="right-aligned no-wrap">@product.kdvliSatis.ToMoneyFormat()</td>
                                <td>@product.tarihSon.ToString("dd.MM.yyyy")</td>
                                <td>@product.KategoriAd</td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>

            <input type="hidden" name="page" id="page" value="@Model.Page" />
            Html.RenderPartial("Pager", Model.PrivateProductPriceListReports);

          }
    </div>

</form>

<script type="text/javascript">
    var totalLengthAvailable = $('.product-search-elements').width();

    /* submit button */
    totalLengthAvailable -= $('.product-search-elements button[type=submit]').outerWidth(true);

    totalLengthAvailable -= 22; /* input padding and border */
    $('input[name=q]').width(totalLengthAvailable);



    function myFunction() {

        var arama = $('input[name=q]');

        var pagerInput = $('input[name=Page]');
        pagerInput.val(1);

        window.location.href = '@Url.Action("PrivateProductPriceListReportExport", "Supplier")' + '?q=' + arama.val();
    }

</script>

Derinsis.B2B/Views/Supplier/ProductListReport.cshtml
@using DerinSIS.B2B.ViewModels
@model ProductListReportModel
@{
    ViewBag.Title = "Ürün Listesi Raporu";
}


<form method="GET" class="pager-form">
    <div class="clearfix product-search-elements" style="margin-bottom: 10px">
        <table>
            <tr>
                <td>
                    <input type="text" id="q" name="q" class="search-box" value="@Model.Sorgu" placeholder="Ürün Adı İçinde Ara" style="margin-bottom:0px" />
                </td>
                <td>
                    <button type="submit" class="btn" data-loading-text="Ara">Ara</button>
                </td>
            </tr>
        </table>
    </div>
    <div class="clearfix">
        @if (Model.ProductListReports.Any())
        {
            <div id="product-list-summary" class="well">
                <div class="clearfix">
                    <div style="float: left; width: 80%; line-height: 30px;">
                        @{  var topSay = Model.ProductListReports.FirstOrDefault().topSay;
                            var topPages = Model.ProductListReports.FirstOrDefault().topSay / Model.PageLength;
                            var topKalan = Model.ProductListReports.FirstOrDefault().topSay % Model.PageLength;
                            if (topKalan > 0)
                            {
                                topPages = topPages + 1;
                            }
                        }
                        @if (Model.Page == 1)
                        {
                            <em>Toplam @topSay sonuç bulundu</em>
                        }
                        else
                        {
                            <em>Sayfa @Model.Page / @topPages sonuç</em>
                        }
                    </div>
                    @*<div>
                        <a href="javascript:myFunctionPdf()">
                            <img width="32" height="32" align="right" src="/Assets/theme/img/Pdf-icon.png" id="pdf" alt="Export to PDF" title="Export to PDF" />
                        </a>
                    </div>*@
                    <div>
                        <a href="javascript:myFunction()">
                            <img width="32" height="32" align="right" src="/Assets/theme/img/Excel-icon.png" id="excel" alt="Export to Excel" title="Export to Excel" />
                        </a>
                    </div>
                </div>
            </div>

            <div class="table-responsive">
                <table id="MyProductTable" class="table table-striped">
                    <thead>
                        <tr>
                            <th style="min-width:70px">Ürün Kod</th>
                            <th style="min-width:80px">Barkod</th>
                            <th style="min-width:500px">Ürün Ad</th>
                            <th style="min-width:750px">Kategori</th>
                            <th style="min-width:80px">Dağıtıcı Kod</th>
                            <th style="min-width:100px">Marka</th>
                            <th style="min-width:80px">Liste Tarihi</th>
                            <th style="text-align:right;min-width:80px">Net Alış</th>
                            <th style="text-align:right;min-width:80px">Kdvli Alış</th>
                            <th style="text-align:right;min-width:80px">Satış</th>
                            <th style="text-align:right;min-width:80px">Kdvli Satış</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model.ProductListReports)
                        {
                            <tr>
                                <td>@product.stkKod</td>
                                <td>@product.barkod</td>
                                <td data-toggle="tooltip" title="@product.stkAd">@product.stkAd.ToString().TruncateAtWord(45)</td>
                                <td>@product.KategoriAd</td>
                                <td>@product.dagiticiKod</td>
                                <td>@product.mrkAd</td>
                                <td>@product.listelemeTarih.ToString("dd.MM.yyyy")</td>
                                <td class="right-aligned no-wrap">@product.netAlis.ToMoneyFormat()</td>
                                <td class="right-aligned no-wrap">@product.kdvliAlis.ToMoneyFormat()</td>
                                <td class="right-aligned no-wrap">@product.satis.ToMoneyFormat()</td>
                                <td class="right-aligned no-wrap">@product.kdvliSatis.ToMoneyFormat()</td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>

            <input type="hidden" name="page" id="page" value="@Model.Page" />
                                Html.RenderPartial("Pager", Model.ProductListReports);
                            }
                            else
                            {
                                <div class="alert alert-error">
                                    <h4 class="alert-heading">Kayıt Bulunamadı!</h4>
                                    Lütfen arama koşullarını değiştirip tekrar deneyin.
                                </div>
                            }
    </div>

</form>

<script type="text/javascript">
    var totalLengthAvailable = $('.product-search-elements').width();

    /* submit button */
    totalLengthAvailable -= $('.product-search-elements button[type=submit]').outerWidth(true);

    totalLengthAvailable -= 22; /* input padding and border */
    $('input[name=q]').width(totalLengthAvailable);



    function myFunction() {

        var arama = $('input[name=q]');

        var pagerInput = $('input[name=Page]');
        pagerInput.val(1);

        window.location.href = '@Url.Action("ProductListReportExport", "Supplier")' + '?q=' + arama.val();
    }

    @*function myFunctionPdf() {

        var arama = $('input[name=q]');

        var pagerInput = $('input[name=Page]');
        pagerInput.val(1);

        window.location.href = '@Url.Action("ProductListReportExportPDF", "Supplier")' + '?q=' + arama.val();
    }*@

</script>

Derinsis.B2B/Views/Supplier/ProductStockActionReport.cshtml
@using DerinSIS.B2B.ViewModels
@model ProductStockActionModel
@{
    ViewBag.Title = "Ürün Stok Hareket Raporu";
}


<form method="GET" class="pager-form">
    @{ Html.RenderPartial("DocumentDateFilter", Model.DateFilter); }
    <div class="well">
        @{
            Html.RenderPartial("magazaFiltre");
        }
    </div>
    <div class="clearfix">
        @if (Model.ProductStocks.Any())
        {
            <div id="product-list-summary" class="well">
                <div class="clearfix">
                    <div style="float: left; width: 80%; line-height: 30px;">
                        @{ var topSay = Model.ProductStocks.FirstOrDefault().topSay;
                            var topPages = Model.ProductStocks.FirstOrDefault().topSay / Model.PageLength;
                            var topKalan = Model.ProductStocks.FirstOrDefault().topSay % Model.PageLength;
                            if (topKalan > 0)
                            {
                                topPages = topPages + 1;
                            }
                        }
                        @if (Model.Page == 1)
                        {
                        <em>Toplam @topSay sonuç bulundu</em>
                        }
                        else
                        {
                        <em>Sayfa @Model.Page / @topPages sonuç</em>
                        }
                    </div>
                    <div>
                        <a href="javascript:myFunction()">
                            <img width="32" height="32" align="right" src="/Assets/theme/img/Excel-icon.png" id="excel" alt="Export to Excel" title="Export to Excel" />
                        </a>
                    </div>
                </div>
            </div>
            

            <div class="table-responsive">
                <table id="MyProductTable" class="table table-striped">
                    <thead>
                        <tr>
                            <th style="min-width:70px">Ürün Kod</th>
                            <th style="min-width:90px">Dağıtıcı Kod</th>
                            <th style="min-width:70px">Barkod</th>
                            <th style="min-width:500px">Ürün Ad</th>
                            <th style="text-align:right;min-width:70px">Devir Stok</th>
                            <th style="text-align:right;min-width:80px">Giren Adet</th>
                            <th style="text-align:right;min-width:80px">Çıkan Adet</th>
                            <th style="text-align:right;min-width:70px">Net Stok</th>
                            <th style="text-align:right;min-width:80px">Birim Fiyat</th>
                            <th style="text-align:right;min-width:80px">Stok Tutar</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model.ProductStocks)
                {
                        <tr>
                            <td>@product.stkKod</td>
                            <td>@product.dagiticiKod</td>
                            <td>@product.barkod</td>
                            <td data-toggle="tooltip" title="@product.stkAd">@product.stkAd.ToString().TruncateAtWord(45)</td>
                            <td class="right-aligned no-wrap">@product.devir.ToStokFormat()</td>
                            <td class="right-aligned no-wrap">@product.giren.ToStokFormat()</td>
                            <td class="right-aligned no-wrap">@product.cikan.ToStokFormat()</td>
                            <td class="right-aligned no-wrap">@product.stok.ToStokFormat()</td>
                            <td class="right-aligned no-wrap">@product.fiyat.ToMoneyFormat()</td>
                            <td class="right-aligned no-wrap">@product.stokTutar.ToMoneyFormat()</td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>

            <input type="hidden" name="page" id="page" value="@Model.Page" />
            Html.RenderPartial("Pager", Model.ProductStocks);
        }
        else
        {
            <div class="alert alert-error">
            <h4 class="alert-heading">Kayıt Bulunamadı!</h4>
            Aradığınız tarihler için ürün stoğu bulunamadı.
            Lütfen arama koşullarını değiştirip tekrar deneyin.
            </div>
        }
    </div>

</form>

<script type="text/javascript">
    function myFunction() {

        var mekan = $('input[name="mekanFilter"]');
        var dateString = $('#dateFilter').val().split("-");
        var beginDateString = dateString[0];
        var endDateString = dateString[1];
        if (!endDateString) {
            endDateString = beginDateString;
        }

        window.location.href = '@Url.Action("ProductStockActionReportExport", "Supplier")' + '?mekanFilter=' + mekan.val() + '&ilkTar=' + beginDateString + '&sonTar=' + endDateString;
    }
    
</script>

Derinsis.B2B/Views/Supplier/ProductStockReport.cshtml
@using DerinSIS.B2B.ViewModels
@model ProductStockModel
@{
    ViewBag.Title = "Ürün Stok Raporu";
}


<form method="GET" class="pager-form">
    <div class="clearfix product-search-elements" style="margin-bottom: 10px">
        <table>
            <tr>
                <td>
                    <input type="text" id="q" name="q" class="search-box" value="@Model.Sorgu" placeholder="Ürün Adı İçinde Ara" style="margin-bottom:0px" />
                </td>
                <td>
                    <button type="submit" class="btn" data-loading-text="Ara">Ara</button>
                </td>
            </tr>
        </table>
    </div>
    <div class="well">
        @{
            Html.RenderPartial("magazaFiltre");
        }
    </div>
    <div class="clearfix">
        @if (Model.ProductStocks.Any())
        {
            <div id="product-list-summary" class="well">
                <div class="clearfix">
                    <div style="float: left; width: 80%; line-height: 30px;">
                        @{  var topSay = Model.ProductStocks.FirstOrDefault().topSay;
                            var topPages = Model.ProductStocks.FirstOrDefault().topSay / Model.PageLength;
                            var topKalan = Model.ProductStocks.FirstOrDefault().topSay % Model.PageLength;
                            if (topKalan > 0)
                            {
                                topPages = topPages + 1;
                            }
                        }
                        @if (Model.Page == 1)
                        {
                            <em>Toplam @topSay sonuç bulundu</em>
                        }
                        else
                        {
                            <em>Sayfa @Model.Page / @topPages sonuç</em>
                        }
                    </div>
                    <div>
                        <a href="javascript:myFunction()">
                            <img width="32" height="32" align="right" src="/Assets/theme/img/Excel-icon.png" id="excel" alt="Export to Excel" title="Export to Excel" />
                        </a>
                    </div>
                </div>
            </div>


            <div class="table-responsive">
                <table id="MyProductTable" class="table table-striped">
                    <thead>
                        <tr>
                            <th>Ürün Kod</th>
                            <th>Dağıtıcı kod</th>
                            <th>Barkod</th>
                            <th>Ürün Ad</th>
                            <th style="text-align:right">Stok Miktar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model.ProductStocks)
                        {
                            <tr>
                                <td>@product.stkKod</td>
                                <td>@product.dagiticiKod</td>
                                <td>@product.barkod</td>

                                @if (topPages == Model.Page && product.stkAd == "TOPLAM" && product.stkID == -1)
                                {
                                    <td style="font-weight:bold">@product.stkAd</td>
                                    <td style="font-weight:bold" class="right-aligned no-wrap">@product.stok.ToString("##,##")</td>

                                }
                                else
                                {
                                    <td>@product.stkAd</td>
                                    <td class="right-aligned no-wrap">@product.stok.ToStokFormat()</td>
                                }

                            </tr>
                        }


                    </tbody>
                </table>
            </div>

            <input type="hidden" name="page" id="page" value="@Model.Page" />
                                Html.RenderPartial("Pager", Model.ProductStocks);
                            }
                            else
                            {
                                <div class="alert alert-error">
                                    <h4 class="alert-heading">Kayıt Bulunamadı!</h4>
                                    Lütfen arama koşullarını değiştirip tekrar deneyin.
                                </div>
                            }
    </div>

</form>

<script type="text/javascript">
    var totalLengthAvailable = $('.product-search-elements').width();

    /* submit button */
    totalLengthAvailable -= $('.product-search-elements button[type=submit]').outerWidth(true);

    totalLengthAvailable -= 22; /* input padding and border */
    $('input[name=q]').width(totalLengthAvailable);



    function myFunction() {

        var arama = $('input[name=q]');
        var mekan = $('input[name="mekanFilter"]');

        var pagerInput = $('input[name=Page]');
        pagerInput.val(1);

        window.location.href = '@Url.Action("ProductStockReportExport", "Supplier")' + '?q=' + arama.val() + '&mekanFilter=' + mekan.val();
    }

</script>