Derinsis.B2B/Controllers/ManagementController.cs
namespace DerinSIS.B2B.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using Emails;
    using Helpers;
    using Infrastructure.Auth;
    using Models;
    using ViewModels;

    [B2BAuthorize(AccountType.Supplier | AccountType.Customer, Privilege.YONETIM)]
    public class ManagementController : BaseController
    {
        private readonly Mailer _mailer;
        private readonly SystemSettings _settings;

        public ManagementController(DbEntities db, Mailer mailer, SystemSettings settings) : base(db)
        {
            _mailer = mailer;
            _settings = settings;
        }

        public ActionResult Index()
        {
            return RedirectToAction("CompanyUsers");
        }

        public ActionResult CompanyUsers()
        {
            var admin = CurrentAccount;
            var model = new CompanyUsersModel
            {
                AdminSiparisYetkisi = admin.ytkB2bSiparisYetkisi != 0,
                AdminFaturaYetkisi = admin.ytkB2bFaturaYetkisi != 0,
                AdminMutabakatYetkisi = admin.ytkB2bMutabakatYetkisi != 0,
                AdminSevkiyatYetkisi = admin.ytkB2bSevkiyatYetkisi != 0,

                CompanyUsers = Db.frmYetkili
                                .Where(x => x.frm.frmID == CurrentCompany.frmID)
                                .Where(x => x.ytkB2B != 0)
                                .Select(x => new CompanyUsersModel.CompanyUser
                                {
                                    Id = x.ytkID,
                                    Ad = x.ytkAd,
                                    Eposta = x.ytkEposta,
                                    B2BYoneticisiMi = x.ytkB2B == 3,
                                    Unvan = x.ytkUnvan,

                                    AktifKullaniciMi = x.ytkB2B != 1,

                                    SiparisYetkisi = x.ytkB2bSiparisYetkisi != 0,
                                    FaturaYetkisi = x.ytkB2bFaturaYetkisi != 0,
                                    SevkiyatYetkisi = x.ytkB2bSevkiyatYetkisi != 0,
                                    MutabakatYetkisi = x.ytkB2bMutabakatYetkisi != 0,
                                    SifresiMevcutMu = !string.IsNullOrEmpty(x.ytkSifre),
                                })
                                .ToList(),
            };

            return View(model);
        }

        public ActionResult EditUser(int? id)
        {
            Check.NotNullOr404(id);

            var yetkili = Db.frmYetkili
                .Where(x => x.frm.frmID == CurrentCompany.frmID)
                .Where(x => x.ytkB2B != 3)
                .SingleOrDefault(x => x.ytkID == id);
            Check.NotNullOr404(yetkili);
            Check.CheckOr404(yetkili.ytkB2B != 3);

            var admin = CurrentAccount;

            var model = new EditUserModel
            {
                Id = yetkili.ytkID,
                EPosta = yetkili.ytkEposta,
                Isim = yetkili.ytkAd,
                Unvan = yetkili.ytkUnvan,

                SiparisYetkisi = yetkili.ytkB2bSiparisYetkisi != 0,
                FaturaYetkisi = yetkili.ytkB2bFaturaYetkisi != 0,
                SevkiyatYetkisi = yetkili.ytkB2bSevkiyatYetkisi != 0,
                MutabakatYetkisi = yetkili.ytkB2bMutabakatYetkisi != 0,
                AktifKullanici = yetkili.ytkB2B != 1,

                AdminFaturaYetkisi = admin.ytkB2bFaturaYetkisi != 0,
                AdminSiparisYetkisi = admin.ytkB2bSiparisYetkisi != 0,
                AdminSevkiyatYetkisi = admin.ytkB2bSevkiyatYetkisi != 0,
                AdminMutabakatYetkisi = admin.ytkB2bMutabakatYetkisi != 0,
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult EditUser(int? id, EditUserModel model)
        {
            Check.NotNullOr404(id);

            var yetkili = Db.frmYetkili
                .Where(x => x.frm.frmID == CurrentCompany.frmID)
                .SingleOrDefault(x => x.ytkID == id);
            Check.NotNullOr404(yetkili);
            Check.CheckOr404(yetkili.ytkB2B != 3);

            if (!ModelState.IsValid)
            {
                ShowErrorMessage();
                return View(model);
            }

            bool sonekvar = false;
            var sonEk = Db.drn2ayar.FirstOrDefault(x => x.ayarID == 777);
            if (sonEk != null)
            {
                if (sonEk.ayarDeger != "")
                {
                    sonekvar = true;
                }
            }

            if (model.EPosta.IndexOf('@') < 0)
            {
                if (sonekvar == false)
                {
                    ShowErrorMessage("Sistemde kullanıcı adı e-posta olma zorunluluğu vardır!");
                    return View(model);
                }
                else
                {
                    model.EPosta = model.EPosta + sonEk.ayarDeger;
                }
            }


            var admin = CurrentAccount;

            if (model.EPosta.IndexOf('@') > -1)
            {

                if (sonekvar)
                {
                    var userEmailExtension = model.EPosta.Substring(model.EPosta.IndexOf("@"));
                    if (userEmailExtension.ToLower() != sonEk.ayarDeger.ToLower())
                    {
                        var adminEmailExtension = admin.ytkEposta.Substring(admin.ytkEposta.IndexOf("@"));
                        if (adminEmailExtension.ToLower() == sonEk.ayarDeger.ToLower())
                        {
                            var ytkler = Db.frmYetkili.Where(x => x.ytkFrm == admin.ytkFrm && x.ytkB2B > 2 && !x.ytkEposta.ToLower().Contains(sonEk.ayarDeger.ToLower())).FirstOrDefault();
                            if (ytkler != null)
                            {
                                adminEmailExtension = ytkler.ytkEposta.Substring(ytkler.ytkEposta.IndexOf("@"));
                            }
                        }

                        if (userEmailExtension.ToLowerInvariant() != adminEmailExtension.ToLowerInvariant())
                        {
                            ModelState.AddModelError("EPosta", "Kuruma ait bir e-posta hesabı girmelisiniz.");
                            ShowErrorMessage();
                            return View(model);
                        }
                    }
                }
                else
                {
                    var userEmailExtension = model.EPosta.Substring(model.EPosta.IndexOf("@"));
                    var adminEmailExtension = admin.ytkEposta.Substring(admin.ytkEposta.IndexOf("@"));
                    if (userEmailExtension.ToLowerInvariant() != adminEmailExtension.ToLowerInvariant())
                    {
                        ModelState.AddModelError("EPosta", "Kuruma ait bir e-posta hesabı girmelisiniz.");
                        ShowErrorMessage();
                        return View(model);
                    }
                }




            }




            yetkili.ytkEposta = model.EPosta;
            yetkili.ytkAd = model.Isim;
            yetkili.ytkUnvan = model.Unvan;

            if (admin.ytkB2bFaturaYetkisi != 0)
            {
                yetkili.ytkB2bFaturaYetkisi = (byte)(model.FaturaYetkisi ? 1 : 0);
            }

            if (admin.ytkB2bMutabakatYetkisi != 0)
            {
                yetkili.ytkB2bMutabakatYetkisi = (byte)(model.MutabakatYetkisi ? 1 : 0);
            }


            if (admin.ytkB2bSiparisYetkisi != 0)
            {
                yetkili.ytkB2bSiparisYetkisi = (byte)(model.SiparisYetkisi ? 1 : 0);
            }

            if (admin.ytkB2bSevkiyatYetkisi != 0)
            {
                yetkili.ytkB2bSevkiyatYetkisi = (byte)(model.SevkiyatYetkisi ? 1 : 0);
            }

            if (yetkili.ytkB2B != 3)
            {
                if (model.AktifKullanici)
                {
                    yetkili.ytkB2B = 2;
                }
                else
                {
                    yetkili.ytkB2B = 1;
                }
            }

            Db.SaveChanges();

            ShowSuccessMessage("Kullanıcı bilgileri güncellenmiştir.");
            return RedirectToAction("CompanyUsers");
        }

        [HttpPost]
        public ActionResult ResetUserPassword(int? id)
        {
            Check.NotNullOr404(id);

            //var user = Db.frmYetkili
            //    .Where(x => x.ytkFrm == CurrentCompany.frmID)
            //    .SingleOrDefault(x => x.ytkID == id);
            //Check.NotNullOr404(user);

            //if(string.IsNullOrWhiteSpace(user.ytkEposta))
            //{
            //    ShowErrorMessage("Kullanıcının E-posta adresi mevcut değil. Lütfen önce kullanıcı bilgilerini güncelleyiniz.");
            //    return RedirectToAction("CompanyUsers");
            //}
            //var resetlemeTalebi = new b2bSifreResetlemeTalep
            //                      {
            //                          frmYetkili = user,
            //                          eposta = user.ytkEposta,
            //                          gKisi = CurrentAccount != null ? CurrentAccount.ytkInsID : 0,
            //                          gTarih = DateTime.Now,
            //                          talepDrm = 0,
            //                          Hash = Guid.NewGuid().ToString(),
            //                      };
            //Db.b2bSifreResetlemeTalep.Add(resetlemeTalebi);
            //Db.SaveChanges();

            //// resetleme mailini gönder
            //var mailModel = new ResetPasswordEmailModel
            //{
            //    KullaniciIsmi = user.ytkAd,
            //    ResetUrl = _settings.SiteAdresi + Url.Action("RecoverPasswordComplete", "Account", new { id = resetlemeTalebi.Hash }),
            //};
            //_mailer.SendResetPasswordMail(CurrentAccount, user.ytkEposta.ToLowerInvariant().Trim(), mailModel);

            return RedirectToAction("ResetUserPasswordComplete", new { id });
        }

Derinsis.B2B/Views/Management/CompanyUsers.cshtml
@model DerinSIS.B2B.ViewModels.CompanyUsersModel

@{
    ViewBag.Title = "Kullanıcılar";
    ViewBag.SubTitle = "Firma Yönetimi";
}


<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th>İsim</th>
            <th>Ünvan</th>
            <th>E-Posta</th>
            
            @if(Model.AdminSiparisYetkisi)
            {
                <th class="center-aligned">Sipariş</th>    
            }
            
            @if(Model.AdminSevkiyatYetkisi)
            {
                <th class="center-aligned">Sevkiyat</th>    
            }
            
            @if(Model.AdminFaturaYetkisi)
            {
                <th class="center-aligned">Fatura</th>    
            }
            
            @if(Model.AdminMutabakatYetkisi)
            {
                <th class="center-aligned">Cari</th>    
            }
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var yetkili in Model.CompanyUsers)
        {
            <tr>
                <td width="120">
                   

                    @if (yetkili.B2BYoneticisiMi)
                    {
                        <a href="#" class="btn btn-info disabled">
                            <i class="icon-user icon-white"></i>
                        </a>
                        <a href="#" class="btn btn-danger disabled">
                            <i class="icon-lock icon-white"></i>
                        </a>
                    }
                    else
                    {
                        <a href="@Url.Action("EditUser", "Management", new { id = yetkili.Id })" class="btn btn-info" rel="tooltip" title="Kullanıcı Bilgilerini Güncelle">
                            <i class="icon-user icon-white"></i>
                        </a>
                        
                        <a href="#" class="btn btn-danger" data-password-reset="@yetkili.Id" rel="tooltip" title="Kullanıcı Şifresini Sıfırla">
                            <i class="icon-lock icon-white"></i>
                        </a>
                    }
                </td>
                <td>@yetkili.Ad</td>
                <td>@yetkili.Unvan</td>
                <td>@yetkili.Eposta</td>
                
                @if(Model.AdminSiparisYetkisi)
                {
                    <td class="center-aligned">
                        @if (yetkili.SiparisYetkisi)
                        {
                            <i class="icon-ok"></i>
                        }
                    </td>    
                }
                
                @if(Model.AdminSevkiyatYetkisi)
                {
                    <td class="center-aligned">
                        @if (yetkili.SevkiyatYetkisi)
                        {
                            <i class="icon-ok"></i>
                        }
                    </td>
                }
                
                @if(Model.AdminFaturaYetkisi)
                {
                    <td class="center-aligned">
                        @if (yetkili.FaturaYetkisi)
                        {
                            <i class="icon-ok"></i>
                        }
                    </td>
                }
                        
                @if (Model.AdminMutabakatYetkisi)
                {
                    <td class="center-aligned">
                        @if (yetkili.MutabakatYetkisi)
                        {
                            <i class="icon-ok"></i>
                        }
                    </td>
                }
                <td>
                    @if (yetkili.B2BYoneticisiMi)
                    {
                        <span class="label label-info">YÖNETİCİ</span>
                    }
                    
                    @if (!yetkili.AktifKullaniciMi)
                    {
                        <span class="label label-important">KAPALI</span>
                    }
                    else
                    {
                        var hasError = false;
                        if (!yetkili.SifresiMevcutMu)
                        {
                            <span class="label label-warning" data-title="Kullanıcı Şifresi" data-placement="left" data-content="Bu kullanıcı için henüz bir şifre oluşturulmamış.<br /><br /><strong><em>Oluşturmak için soldaki kilit simgeli şifre sıfırlama butonunu kullanabilirsiniz.</em></strong>">ŞİFRE YOK</span>
                            
                            { hasError = true; }
                        }

                        if (!yetkili.MutabakatYetkisi && !yetkili.SevkiyatYetkisi && !yetkili.SiparisYetkisi && !yetkili.FaturaYetkisi)
                        {
                            <span class="label label-warning" data-title="Kullanıcı Yetkileri" data-placement="left" data-content="Bu kullanıya atanmış herhangi bir yetki bulunmamaktadır. Bu sebeple kullanıcı sisteme girişi yapamayacaktır.<br /><br /><strong><em>Kullanıya yetki atamak için soldaki 'Kullanıcı Bilgilerini Güncelle' butonunu kullanabilirsiniz.</em></strong>">YETKİ YOK</span>
                        
                            { hasError = true; }
                        }

                        if (!hasError)
                        {
                            <span class="label label-success">AKTİF</span>     
                        }
                    }
                </td>
            </tr>
        }
    </tbody>
</table>


@section javascripts
{
    <script type="text/javascript">
        $(document).ready(function () {

            $('[data-title]').popover({ placement: 'top' });

            $('[data-password-reset]').click(function () {
                var t = $(this);
                var id = t.data('password-reset');

                $('<form />')
                    .attr('method', 'POST')
                    .attr('action', '@Url.Action("ResetUserPassword")')
                    .html('<input type="hidden" name="id" value="' + id + '" />')
                    .appendTo('body')
                    .submit();
            });
        });
    </script>
}

Derinsis.B2B/Views/Management/EditUser.cshtml
@model DerinSIS.B2B.ViewModels.EditUserModel

@{
    ViewBag.Title = "Kullanıcı Düzenle";
    ViewBag.SubTitle = "Firma Yönetimi";
}


<form method="POST" action="" class="form-horizontal">
    <fieldset>
    
        <div class="control-group @(ViewData.ModelState.IsValidField("EPosta") ? "" : "error")">
            <label for="EPosta" class="control-label">E-Posta Adresi</label>
            <div class="controls">
                @Html.EditorFor(x => x.EPosta)    
            
                @if (!ViewData.ModelState.IsValidField("EPosta"))
                {
                    <span class="help-inline">@Html.ValidationMessage("EPosta")</span>
                }    
            </div>
        </div>
        
        <div class="control-group @(ViewData.ModelState.IsValidField("Isim") ? "" : "error")">
            <label for="Isim" class="control-label">İsim</label>
            <div class="controls">
                @Html.EditorFor(x => x.Isim)    
            
                @if (!ViewData.ModelState.IsValidField("Isim"))
                {
                    <span class="help-inline">@Html.ValidationMessage("Isim")</span>
                }    
            </div>
        </div>
        
        <div class="control-group @(ViewData.ModelState.IsValidField("Unvan") ? "" : "error")">
            <label for="Unvan" class="control-label">Ünvan</label>
            <div class="controls">
                @Html.EditorFor(x => x.Unvan)    
            
                @if (!ViewData.ModelState.IsValidField("Unvan"))
                {
                    <span class="help-inline">@Html.ValidationMessage("Unvan")</span>
                }    
            </div>
        </div>

        
        @if (Model.AdminSiparisYetkisi)
        {
            <div class="control-group">
                <label for="EPosta" class="control-label">Sipariş Yetkisi</label>
                <div class="controls">
                    @Html.EditorFor(x => x.SiparisYetkisi)
                </div>
            </div>
        }
        
        @if (Model.AdminSevkiyatYetkisi)
        {
            <div class="control-group">
                <label for="AdminSevkiyatYetkisi" class="control-label">Sevkiyat Yetkisi</label>
                <div class="controls">
                    @Html.EditorFor(x => x.SevkiyatYetkisi)
                </div>
            </div>
        }
        
        @if (Model.AdminFaturaYetkisi)
        {
            <div class="control-group">
                <label for="AdminFaturaYetkisi" class="control-label">Fatura Yetkisi</label>
                <div class="controls">
                    @Html.EditorFor(x => x.FaturaYetkisi)        
                </div>
            </div>
        }
        
        @if (Model.AdminMutabakatYetkisi)
        {
            <div class="control-group">
                <label for="AdminMutabakatYetkisi" class="control-label">Mutabakat Yetkisi</label>
                <div class="controls">
                    @Html.EditorFor(x => x.MutabakatYetkisi)
                </div>
            </div>
        }
        
        
        <div class="control-group">
            <label for="AktifKullanici" class="control-label">Aktif Kullanıcı Mı?</label>
            <div class="controls">
                @Html.EditorFor(x => x.AktifKullanici)        
            </div>
        </div>

        @Html.EditorFor(x => x.AdminFaturaYetkisi)
        @Html.EditorFor(x => x.AdminMutabakatYetkisi)
        @Html.EditorFor(x => x.AdminSevkiyatYetkisi)
        @Html.EditorFor(x => x.AdminSiparisYetkisi)
        <div class="form-actions">
            <input type="submit" class="btn btn-large btn-info" data-loading-text="Kaydediliyor..." value="Kaydet" />
        </div>
    </fieldset>
</form>

Derinsis.B2B/Views/Management/ResetUserPasswordComplete.cshtml
@{
    ViewBag.Title = "Kullanıcı Şifresini Sıfırla";
    ViewBag.SubTitle = "Firma Yönetimi";
}


<div class="alert alert-success">
    @*Kullanıcıya şifresini oluşturmak için gerekli bilgiler mail yoluyla gönderilmiştir.*@
    Kullanıcı şifresini oluşturmak için yetkiliye başvurunuz.
</div>

<div>
    Kullanıcılar sayfasına geri dönmek için 
    <a href="@Url.Action("CompanyUsers")">lütfen tıklayın.</a>
</div>

Derinsis.B2B/Views/Management/_ManagementLayout.cshtml
@{
    Layout = "~/Views/Shared/_ContentLayout.cshtml";
}


@section sidebar
{
    <div class="well">
        <ul class="nav nav-list">
            
            <li class="nav-header">Firma Yönetimi</li>
            @Url.SidebarLink("Kullanıcılar", "CompanyUsers", "Management", "user")
        </ul>
    </div>
}


@RenderBody()


@section javascripts
{
    @RenderSection("javascripts", required: false)
}