Backup/Derinsis.B2B/Controllers/StoreController.cs
using System.Collections.ObjectModel;
using System.Data;

namespace DerinSIS.B2B.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Helpers;
    using Helpers.Html;
    using Helpers.Paging;
    using Infrastructure.Auth;
    using Models;
    using ViewModels;

    [B2BAuthorize(AccountType.Customer, Privilege.SIPARIS)]
    public class StoreController : BaseController
    {
        public StoreController(DbEntities db): base(db)
        {
        }
        
        #region Product List

        public ActionResult Index(string q, int? categoryId, int? brandId, int? producerId, int? page,string kmp,string price,string priceLabel)
        {

            var model = new ProductListModel();
            model.OzelFiyat = kmp == "on" ? true : false;

            var query = (
                            from urnSatis_vw in Db.urnSatis_vw
                            join urnBarkod_vw in Db.urnBarkod_vw on urnSatis_vw.stkID equals urnBarkod_vw.urnBrkdStkID
                            select new
                                {
                                    urnSatis_vw.stkID,
                                    urnSatis_vw.stkKod,
                                    urnSatis_vw.stkAd,
                                    urnSatis_vw.mrkAd,
                                    urnSatis_vw.grpAd,
                                    urnSatis_vw.urnKtgrID,
                                    urnSatis_vw.urnKtgrID1,
                                    urnSatis_vw.urnKtgrID2,
                                    urnSatis_vw.urnKtgrID3,
                                    urnSatis_vw.urtID,
                                    urnSatis_vw.urnMrkID,
                                    urnSatis_vw.urnGrpID,
                                    urnBarkod_vw.barkod,
                                    urnSatis_vw.rtb,
                                }
                        )
                .AsQueryable();

            if (!string.IsNullOrWhiteSpace(q))
            {

                model.Sorgu = q;
                if (isNumeric(q) && q.Length >= 8)
                {
                    var barkodlar = Db.urnBrkd.Where(x => x.urnBarkod.Contains(q)).Select(x=>x.urnBrkdStkID).ToList();
                    query = query.Where(x => barkodlar.Contains(x.stkID));
                }
                else
                {
                    var qstr = q.Split(' ').Select(x => x.ToLower()).ToArray();
                    query = query.Where(x =>
                                        qstr.All(y => x.stkAd.Contains(y)) ||
                                        x.stkKod.Contains(q) ||
                                        x.mrkAd.Contains(q) ||
                                        x.grpAd.Contains(q));
                }
            }

            /* Category Filter */
            if(categoryId != null)
            {
                var kategori = Db.urnKtgrAg_vw.Single(x => x.kID == categoryId);
                model.KategoriIdFiltresi = kategori.kID;
                model.KategoriFiltreEtiketi = kategori.kAd;

                query = query.Where(x => x.urnKtgrID == kategori.k0);

                if (kategori.k1 != 0)
                {
                    query = query.Where(x => x.urnKtgrID1 == kategori.k1);
                }

                if(kategori.k2 != 0)
                {
                    query = query.Where(x => x.urnKtgrID2 == kategori.k2);
                }
                if (kategori.k3 != 0)
                {
                    query = query.Where(x => x.urnKtgrID3 == kategori.k3);
                }
            }

            /* Producer Filter */
            if(producerId != null)
            {
                var uretici = Db.urnMrkUrt.Single(x => x.urtID == producerId);
                model.UreticiIdFiltresi = uretici.urtID;
                model.UreticiFiltreEtiketi = uretici.urtAd;
                
                query = query.Where(x => x.urtID == uretici.urtID);
            }

            /* Brand Filter */
            if(brandId != null)
            {
                var marka = Db.urnMrk.Single(x => x.mrkID == brandId);
                model.MarkaIdFiltresi = marka.mrkID;
                model.MarkaFiltreEtiketi = marka.mrkAd;

                query = query.Where(x => x.urnMrkID == marka.mrkID);
                

            }
            if (model.OzelFiyat)
            {
                var ekIndirim = Db.fytOzl
                    .Where(x => x.fTip == 4)
                    //.Where(x => x.fFrmID == 0)
                    .Where(x => x.fTarih <= DateTime.Today.Date && x.fTarihSon >= DateTime.Today.Date)
                    .Where(x => x.fTur == 0)
                    .Where(x => x.onay == 1);
                query = query.Where(x => ekIndirim.Any(y => y.fStkID == x.stkID));
            }
            if (price != null && price != "")
            {
                var esik = price.Split('-');
                int min = int.Parse(esik[0]);
                int max = esik[1] != "" ? int.Parse(esik[1]) : 99999999;
                model.FiyatFiltresi = price;
                model.FiyatFiltreEtiketi = priceLabel;

                query = query.
                    Where(x => 
                        Db.urn.
                       Join(Db.posOdeme,urun=>urun.fiyatSDvz,odeme=>odeme.odemeDvzID,(urun,odeme)=>new {Urun=urun,Odeme=odeme}).
                        Where(x1=>Db.urnSatis_vw.Any(x2=>x2.stkID==x1.Urun.stkID)).
                            Where(x3 => (x3.Urun.fiyatSDvz == 1 ? x3.Urun.fiyatS : x3.Urun.fiyatS * x3.Odeme.odemeKur) >= min && (x3.Urun.fiyatSDvz == 1 ? x3.Urun.fiyatS : x3.Urun.fiyatS * x3.Odeme.odemeKur) <= max).Any(x4 => x4.Urun.stkID == x.stkID));
            }
            
            // Arama Sonuç Listesi
            // Sıralı bir şekilde Model ve/veya Ürünler içerir.
            var searchResultList = query
                .GroupBy(x => new { Id = x.urnGrpID == 0 ? x.stkID : x.urnGrpID, Rutbe = x.rtb, Isim = x.urnGrpID == 0 ? x.stkAd : x.mrkAd, ModelMi = x.urnGrpID != 0 })
                .OrderBy(x=>x.Key.Rutbe).ThenBy(x=>x.Key.Isim)
                .ToPagedList(page ?? 1, 28);


            // Arama sonuçlarında bulunanan ürünlerin listesi
            var urunIdleri = searchResultList.Where(x => x.Key.ModelMi == false).Select(x => x.Key.Id);
            var urunler = (from urn in Db.urnSatis_vw
                           join mainUrn in Db.urn on urn.stkID equals mainUrn.stkID
                           join posOdeme in Db.posOdeme on mainUrn.fiyatSDvz equals posOdeme.odemeDvzID
                           where urunIdleri.Contains(urn.stkID)
                           let barkod = Db.urnBarkod_vw.FirstOrDefault(x => x.urnBrkdStkID == urn.stkID)
                           let mrkIndirim = Db.sakMrk_vw
                               .Where(x => x.skFrmID == CurrentCompany.frmID)
                               .Where(x => x.skTur == CurrentCompany.frmVadeTur)
                               .FirstOrDefault(x => x.skMrkID == urn.urnMrkID)
                           let ekIndirim = Db.fytOzl
                               .Where(x => x.fStkID == urn.stkID)
                               .Where(x => x.fTip == 4)
                               //.Where(x => x.fFrmID == 0)
                               .Where(x => x.fTarih <= DateTime.Today.Date && x.fTarihSon >= DateTime.Today.Date)
                               .Where(x => x.fTur == 0)
                               .Where(x => x.onay == 1)
                               .OrderByDescending(x => x.fTarih)
                               .ThenByDescending(x => x.fID)
                               .FirstOrDefault()
                           select new ProductListModel.ProductModel
                                      {
                                          Id = urn.stkID,
                                          Isim = urn.stkAd,
                                          StokKodu = urn.stkKod,
                                          Barkod = barkod != null ? barkod.barkod : "",
                                          KDVHaricFiyat = urn.fiyatS,
                                          Indirim1 = mrkIndirim != null ? mrkIndirim.skY1 : 0,
                                          Indirim2 = mrkIndirim != null ? mrkIndirim.skY2 : 0,
                                          Indirim3 = mrkIndirim != null ? mrkIndirim.skY3 : 0,
                                          Indirim4 = ekIndirim != null ? ekIndirim.fInd1 : 0,
                                          Birim = posOdeme.odemeKisaAd,
                                          Kur = posOdeme.odemeKur,
                                          Rutbe = urn.rtb,
                                      })
                .ToList()
                .Cast<ProductListModel.ProductListItemModel>();
                                 
                
            // Aramaa sonuçlarında bulunan modellerin listesi
            var modelIdleri = searchResultList.Where(x => x.Key.ModelMi).Select(x => x.Key.Id);
            var modeller = (from urnGrp in Db.urnGrp
                            where modelIdleri.Contains(urnGrp.grpID)
                            let indirim = Db.sakMrk_vw
                                .Where(x => x.skFrmID == CurrentCompany.frmID)
                                .Where(x => x.skTur == CurrentCompany.frmVadeTur)
                                .FirstOrDefault(x => x.skMrkID == urnGrp.grpMrkID)
                            select new ProductListModel.ProductGroupModel
                                   {
                                       Id = urnGrp.grpID,
                                       Isim = urnGrp.grpAd,
                                       Indirim1 = indirim != null ? indirim.skY1 : 0,
                                       Indirim2 = indirim != null ? indirim.skY2 : 0,
                                       Indirim3 = indirim != null ? indirim.skY3 : 0, 

Backup/Derinsis.B2B/Views/Store/CartMenuElement.cshtml
@model DerinSIS.B2B.ViewModels.CartMenuElementModel
           
<li>
    <a href="@Url.Action("Cart", "Store")" class="cartelement" data-placement="bottom">
        
        <i class="icon-shopping-cart icon-white"></i>
        @Model.AktifSepetIsmi
        
        (<span class="cart-urun-cesidi">@Model.ToplamUrunCesidi</span> Ürün - 
        <span class="cart-kdv-dahil-toplam">@Model.KDVDahilTutar.ToMoneyFormat()</span> TL)
        
        @{
            var lastItem = Model.SonEklenen2Urun.FirstOrDefault();
            var previousItem = Model.SonEklenen2Urun.LastOrDefault();
        }
        <input type="hidden" class="" name="active-cart-name" value="@Model.AktifSepetIsmi" />
        <input type="hidden" class="cart-urun-cesidi" name="cart-urun-cesidi" value="@Model.ToplamUrunCesidi" />
        <input type="hidden" class="cart-kdv-dahil-toplam" name="cart-kdv-dahil-toplam" value="@Model.KDVDahilTutar.ToMoneyFormat()" />
        <input type="hidden" class="cart-last-product" name="last-product" value="@(lastItem != null ? lastItem.UrunIsmi : "")"/>    
        <input type="hidden" class="cart-previous-product" name="previous-product" value="@(previousItem != null ? previousItem.UrunIsmi : "")"/>    
    </a>
</li>

Backup/Derinsis.B2B/Views/Store/CartSidebarElement.cshtml
@model DerinSIS.B2B.ViewModels.CartSidebarElementModel
           
@helper CartTooltipContent() {
    if(Model.ToplamUrunCesidi > 0)
    {
        <h6></h6>
    }
    else
    {
        <h6>ÜRÜN BULUNMAMAKTADIR</h6><br />
    }
}

<div class="well">
    <h6>@Model.AktifSepetIsmi:</h6>
    
    <table class="table">
        <tr>
            <td>ÜRÜN ÇEŞİDİ</td>
            <th class="right-aligned"><span class="cart-urun-cesidi">@Model.ToplamUrunCesidi</span> ÜRÜN ÇEŞİDİ</th>
        </tr>
        <tr>
            <td>TUTAR</td>
            <th class="right-aligned"><span class="cart-kdv-dahil-toplam">@Model.KDVDahilTutar.ToMoneyFormat()</span> TL</th>
        </tr>
    </table>
    
    <a href="@Url.Action("Cart")" class="btn btn-info">
        <i class="icon-shopping-cart icon-white"></i>
        Sepete Git
    </a>
</div>

Backup/Derinsis.B2B/Views/Store/EditCart.cshtml
@model DerinSIS.B2B.ViewModels.EditCartModel
@{
    ViewBag.Title = "Sepeti Düzenle";
}


<div class="well page-actions">
    <a class="btn" href="@Url.Action("MyCarts", "Store")"><i class="icon-chevron-left"></i> Sepetlerime Geri Dön</a>
</div>


@using (Html.BeginForm()) {
    <div>
        <fieldset>

            @Html.EditorForModel()

            <div class="actions">
                <input type="submit" class="btn btn-large btn-info" data-loading-text="Kaydediliyor..." value="Kaydet" />
            </div>
        </fieldset>
    </div>
}

Backup/Derinsis.B2B/Views/Store/MyCarts.cshtml
@model IList<DerinSIS.B2B.ViewModels.MyCartModel>
@{
    ViewBag.Title = "Sepetlerim";
}


<div class="well page-actions right-aligned">
    <a class="btn btn-info" href="@Url.Action("CreateNewCart", "Store")"><i class="icon-plus icon-white"></i> Yeni Sepet Oluştur</a>
</div>


<table class="table table-striped my-carts-table">
    <thead>
        <tr>
            <th>Sepet İsmi</th>
            <th>Açıklamalar</th>
            <th>Mevcut Ürünler</th>
            <th style="width: 150px;">İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var cart in Model)
        {
            <tr>
                <td>
                    <strong>@cart.Isim</strong>
                    
                    @if(cart.AktifMi)
                    {
                        <span class="label label-success">AKTİF SEPET</span>
                    }
                </td>
                <td>@cart.Aciklamalar</td>
                <td>
                    @if(cart.Adet > 0)
                    {
                        <span>@cart.Adet ürün bulunmaktadır.</span>
                    }
                    else
                    {
                        <span>Ürün Yok</span>
                    }
                </td>
                <td class="table-actions">
                    @using (Html.BeginForm("MakeCartActive", "Store", new { id = cart.Id }))
                    {
                        <button type="submit" rel="tooltip" title="Aktif Yap" data-loading-text="..." class="btn btn-success btn-small" @(cart.AktifMi ? "disabled=\"disabled\"": "")>
                            <i class="icon-ok icon-white"></i>
                        </button>
                    }
                    
                    @using(Html.BeginForm("EditCart", "Store", new { id = cart.Id }, FormMethod.Get))
                    {
                        <button type="submit" rel="tooltip" title="Düzenle" class="btn btn-small" data-loading-text="...">
                            <i class="icon-pencil"></i>
                        </button>
                    }
                    
                    <form method="POST" action="@Url.Action("DeleteCart", new {id = cart.Id})" class="delete-cart-form" >
                        <button type="submit" class="btn btn-danger btn-small" data-loading-text="..." rel="tooltip" title="Sil">
                            <i class="icon-remove icon-white"></i>
                        </button>
                    </form>
                        
                </td>
            </tr>
        }
    </tbody>
</table>


@section javascripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $('.delete-cart-form').submit(function () {
                if (!confirm("Bu sepeti silmek istediğinizden emin misiniz?")) {
                    return false;
                }
            });
        });
    </script>
}

Backup/Derinsis.B2B/Views/Store/OrderCompleted.cshtml
@model DerinSIS.B2B.ViewModels.OrderCompletedModel
@{
    ViewBag.Title = "Siparişiniz Tamamlandı";
}


<div class="alert alert-info">
    <strong>Siparişiniz Başarıyla Tamamlanmıştır.</strong>
    <p>
        Siparişinizi takip etmek için Sipariş Detayına bakabilirsiniz.
    </p>
    <p>
        <a class="btn btn-info" href="@Url.Action("OrderDetail", "Sales", new { id = Model.SiparisId })">
            Sipariş Detaylarına Git <i class="icon-chevron-right icon-white"></i>
        </a>
    </p>
</div>
@if(!string.IsNullOrWhiteSpace(Model.SiparisNotu))
{
    <div class="well">
        <h6>SİPARİŞ NOTU:</h6>
        @Model.SiparisNotu.PadRight(33)<br />
        @Model.SiparisNotu.PadRight(33).PadLeft(33).Substring(33)<br />
        @Model.SiparisNotu.PadRight(33).PadLeft(66).Substring(66)<br />
    </div>    
}

<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Stok Kodu</th>
            <th>Ürün</th>
            <th>KDV Hariç Net</th>
            <th>KDV Dahil Net</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var satir in Model.SiparisSatirlari)
        {
            <tr>
                <th>@satir.Sira</th>
                <td>@satir.StokKodu</td>
                <td>
                    <a href="@Url.Action("ProductDetail", "Store", new { id = satir.UrunId })">@satir.UrunAdi</a>
                </td>
                <td class="right-aligned">@satir.Tutar.ToMoneyFormat() TL</td>
                <td class="right-aligned">@satir.Matrah.ToMoneyFormat() TL</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <th colspan="3" class="right-aligned">TOPLAM:</th>
        <th class="right-aligned">@Model.SiparisSatirlari.Sum(x => x.Tutar).ToMoneyFormat() TL</th>
        <th class="right-aligned">@Model.SiparisSatirlari.Sum(x => x.Matrah).ToMoneyFormat() TL</th>
    </tfoot>
</table>

Backup/Derinsis.B2B/Views/Store/OrderSummary.cshtml
@model DerinSIS.B2B.ViewModels.OrderSummaryModel
@{
    ViewBag.Title = "Sipariş Onayı";
}



<div class="well">
    <h3>Toplam Fiyat: @Model.Urunler.Sum(x => x.TotalPrice).ToString("N") TL</h3>
</div>

<div class="well">
    <h6>SEVK ADRESİ</h6>
    <h4>@Model.AdresAdi</h4>
    <p>
        @Model.AdresSatiri1<br />
        @Model.AdresSatiri2<br />
        @Model.AdresPostaKodu<br />
        @Model.AdresIlce / @Model.AdresIl
    </p>
</div>

<div class="well">
    <table class="table table-striped">
        <thead>
            <th>Ürün</th>
            <th>Birim Fiyat</th>
            <th>İndirimli Birim Fiyat</th>
            <th>Adet</th>
            <th>Toplam Fiyat</th>
        </thead>
        @foreach(var item in Model.Urunler)
        {
            <tr>
                <td><strong>@item.ProductName</strong></td>
                <td>@item.ProductUnitPrice.ToString("N") TL</td>
                <td>@item.ProductUnitDiscountedPrice.ToString("N") TL</td>
                <td>@item.Quantity.ToString("N")</td>
                <td>@item.TotalPrice.ToString("N")</td>
            </tr>
        }
    </table>
</div>

<form id="" method="POST" action="@Url.Action("CompleteOrder", "Store", new { addressId = Model.AdresId })">
    
    <div class="well">
        <h6>SİPARİŞ NOTU:</h6>
        <div class="row-fluid">
            <div>
                <input type="text" name="sipNotSatiri1" maxlength="33" class="span5" />
            </div>
            <div>
                <input type="text" name="sipNotSatiri2" maxlength="33" class="span5" />
            </div>
            <div>
                <input type="text" name="sipNotSatiri3" maxlength="33" class="span5" />
            </div>
        </div>
        
    </div>

    <div class="form-actions">
        <button type="submit" class="btn btn-success btn-large" data-loading-text="Sipariş Tamamlanıyor...">
            <i class="icon-shopping-cart icon-white"></i>
            Siparişi Tamamla
        </button>    
    </div>
</form>

Backup/Derinsis.B2B/Views/Store/Prices.cshtml
@model DerinSIS.B2B.ViewModels.PricesModel

<ul  class="nav bs-sidenav">
    <h5>Fiyat Aralığı</h5>
    @foreach(var price in Model.Prices)
    {
        <li><a href="#" data-fiyataraligi=@price.Name>@price.Name TL</a></li>        
    }
    </ul>

Backup/Derinsis.B2B/Views/Store/ProductBrandTree.cshtml
@model dynamic

Backup/Derinsis.B2B/Views/Store/ProductGroupDetail.cshtml
@model DerinSIS.B2B.ViewModels.ProductGroupDetailModel

@{
    ViewBag.Title = Model.ModelAdi;
}


<div class="row">
    <div class="span4">
        @{ Html.RenderAction("ProductGroupSlideShow", "Thumbnail", new { id = Model.Id }); }
    </div>

    <div class="span5">
        
        <div class="labeled-breadcrumb-container">
            @if (Model.Kategori0Id != 0)
            {
                <div class="breadcrumb-label">Kategori</div>
                <ul class="breadcrumb">
                    <li>
                        <a href="#" data-product-search-toggle="categoryId" data-product-search-filter="@Model.Kategori0Id">@Model.Kategori0Ad</a>
                        @if (Model.Kategori1Id != 0)
                        {
                            <span class="divider">/</span>
                        }
                    </li>
                    @if (Model.Kategori1Id != 0)
                    {
                        <li>
                            <a href="#" data-product-search-toggle="categoryId" data-product-search-filter="@Model.Kategori1Id">@Model.Kategori1Ad</a>
                
                            @if (Model.Kategori2Id != 0)
                            {
                                <span class="divider">/</span>
                            }  
                        </li>
                    }
            
                    @if (Model.Kategori2Id != 0)
                    {
                        <li>
                            <a href="#" data-product-search-toggle="categoryId" data-product-search-filter="@Model.Kategori2Id">@Model.Kategori2Ad</a>
                        </li>
                    }
            
                </ul>
            }
            
        </div>
        
        <div class="labeled-breadcrumb-container">
            <div class="breadcrumb-label">Marka</div>
            <ul class="breadcrumb">
                <li>
                    <a href="#" data-product-search-toggle="producerId" data-product-search-filter="@Model.UreticiId">@Model.UreticiAdi</a>
                    <span class="divider">/</span>
                </li>
                <li>
                    <a href="#" data-product-search-toggle="brandId" data-product-search-filter="@Model.MarkaId">@Model.MarkaAdi</a>
                </li>
            </ul>    
        </div>
        
        
        <div class="row">
            <div class="span3">
                <div class="well">
                    <table class="table">
                        <tr>
                            <td>Satış Fiyatı</td>
                            <td class="right-aligned">@Model.KDVHaricSatisFiyati.ToMoneyFormat() TL</td>
                        </tr>
                        <tr>
                            <td>İndirimler</td>
                            <td class="right-aligned">
                                @Model.ToplamIndirim.ToMoneyFormat() TL
                            </td>
                        </tr>
                        <tr>
                            <td>KDV</td>
                            <td class="right-aligned">%@Model.KDVOrani</td>
                        </tr>
                        <tr>
                            <th>Toplam</th>
                            <th class="right-aligned">@Model.KDVDahilToplam.ToMoneyFormat() TL</th>
                        </tr>
                    </table>
                </div>
            </div>

            <div class="span2 add-to-cart-from-details-page">
                @{
                    var indirimler = new[] { Model.Indirim1, Model.Indirim2, Model.Indirim3 };
                }
                                
                @if (indirimler.Any(x => x > 0))
                {
                    <span class="label label-info label-big">
                        %@string.Join("+", indirimler.Where(x => x > 0).Select(x => x.ToQuantityFormat()))     
                    </span> 
                }
                
                @if(Model.Indirim4 > 0)
                {
                    if(indirimler.Any(x => x > 0))
                    {
                        <div style="text-align:center; margin-top: -12px; font-size: 20px;">
                            +
                        </div>     
                    }
                    <span class="label label-important label-big">
                        %@Model.Indirim4.ToQuantityFormat()
                    </span>
                }
            </div>
        </div>
        
    </div>
</div>

<hr />

<div class="row">
    <div class="span9">
        <table class="table product-list">
            <thead>
                <tr>
                    <th>Stok Kodu</th>
                    <th>Ürün</th>
                    <th>Barkod</th>
                    <th class="right-aligned">İndirim</th>
                    <th class="right-aligned">Tutar</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var product in Model.Products)
                {
                    var urunIndirimleri = new[] { product.Indirim1, product.Indirim2, product.Indirim3 };
                    
                    <tr>
                        <td>@product.StokKodu</td>
                        <td>
                            <a href="@Url.Action("ProductDetail", "Store", new { id = product.Id })">
                                @product.Isim
                            </a>
                        </td>
                        <td>@product.Barkod</td>
                        <td class="right-aligned">
                            @if(urunIndirimleri.Any(x => x > 0))
                            {
                                <span class="badge badge-info">
                                    <i class="icon-download-alt icon-white"></i>
                                    %@string.Join(" + ", urunIndirimleri.Select(x => x.ToQuantityFormat()))
                                </span>    
                            }
                            
                            @if(product.Indirim4 > 0)
                            {
                                <span class="badge badge-success">
                                    <i class="icon-arrow-down icon-white"></i>
                                    %@product.Indirim4.ToQuantityFormat()
                                </span>    
                            }
                        </td>
                        <td class="right-aligned">@product.KDVHaricNet.ToMoneyFormat() TL</td>
                        <td class="right-aligned" width="100">
                            <form class="form-horizontal add-to-cart-form product-list-1-add-to-cart-form" action="#">
                                <div class="input-append input-prepend">
                                    <span class="add-on"><i class="icon-shopping-cart"></i></span>
                                    <input type="text" name="quantity" value="" />
                                    <input type="hidden" name="productId" value="@Model.Id" />
                                    <button class="btn btn-success add-to-cart" type="button">Ekle!</button>
                                </div>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Backup/Derinsis.B2B/Views/Store/ProductListItemGroup.cshtml
@model DerinSIS.B2B.ViewModels.ProductListItemGroupModel

<tr>
    <td><a href="@Url.Action("ProductGroupDetail", new { id = Model.GroupId })">@Model.Name</a></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td class="product-list-action">
        <button class="btn btn-warning show-group-details" data-group-id="@Model.GroupId" data-toggle="button"><i class="icon-chevron-down icon-white"></i></button>
    </td>
</tr>
<tr id="group-details-@Model.GroupId" style="display: none" class="group-details">
    <td colspan="4">
        <div class="well">
            <table class="table">
                @foreach (var subProduct in Model.Items)
                {
                                            
                    <tr>
                        <td>
                            <a href="@Url.Action("ProductDetail", "Store", new { id = subProduct.Id })">
                                @subProduct.Name
                            </a>
                        </td>
                        <td>@subProduct.Fiyat.ToString("N") TL</td>
                        <td class="product-list-action">
                            <input type="text" value="" name="product-quantity" data-product-id="@subProduct.Id" data-product-name="@subProduct.Name"/>
                        </td>
                        <td>
                             <button type="button" class="btn btn-info add-to-cart-single"><i class="icon-plus-sign icon-white"></i></button>
                        </td>
                    </tr>
                }
            </table>    
        </div>
        
    </td>
</tr>