Backup/Derinsis.B2B/Controllers/AccountingController.cs
using System.Web.Routing;

namespace DerinSIS.B2B.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using Helpers;
    using Infrastructure;
    using Infrastructure.Auth;
    using Models;
    using ViewModels;

    [B2BAuthorize(AccountType.Supplier | AccountType.Customer, Privilege.FATURA | Privilege.CARI)]
    public class AccountingController : BaseController
    {
        private readonly SystemSettings _settings;

        public AccountingController(DbEntities db, SystemSettings settings) : base(db)
        {
            _settings = settings;
        }

        #region Dashboard
        
        public ActionResult Index()
        {
            // Banka Hesap Bilgileri
            var bankaHesapBilgileri = Db.frmBnk
                .Where(x => x.frmBnkFirmaID == CurrentCompany.frmID)
                .Select(x => new AccountingDashboardModel.BankaHesapBilgisi
                             {
                                 HesapNo = x.frmBnkHesapNo,
                                 Sube = x.bnkSube.subeAd,
                                 Banka = x.bnkSube.bnk.bankaAd,
                             })
                .ToList();

            // Ödenmemiş Faturalar
            var odenmemisFaturalar = Db.car
                .Where(x => x.cKod == CurrentCompany.frmID)
                .Where(x => x.cKalan != 0)
                .Join(Db.fat, car => car.cFatID, fat => fat.eID, (car, fat) => new {car, fat})
                .OrderByDescending(x => x.car.cTarih)
                .Select(x => new AccountingDashboardModel.OdenmemisFatura
                             {
                                 Id = x.fat.eID,
                                 KalanTutar = x.car.cKalan,
                                 EvrakNo = x.fat.eNo,
                                 FaturaTarihi = x.fat.eTarih,
                                 VadeTarihi = x.fat.eTarihV,
                             })
                .ToList();

            // Bakiye Bilgileri
            var borc = Db.car
                           .Where(x => x.cKod == CurrentCompany.frmID)
                           .Where(x => x.cBA == 1 /* Borç */)
                           .Sum(x => (decimal?) x.cTutar) ?? 0;

            var alacak = Db.car
                             .Where(x => x.cKod == CurrentCompany.frmID)
                             .Where(x => x.cBA == 0 /* Alacak */)
                             .Sum(x => (decimal?) x.cTutar) ?? 0;


            // Model
            var model = new AccountingDashboardModel
                        {
                            BankaHesapBilgileri = bankaHesapBilgileri,
                            OdenmemisFaturalar = odenmemisFaturalar,
                            Borc = Math.Abs(borc),
                            Alacak = Math.Abs(alacak),
                            Bakiye = Math.Abs(borc) - Math.Abs(alacak),
                            SistemMutabakatTarihi = CurrentCompany.frmCariTarih,
                            FirmaMutabakatTarihi = CurrentCompany.frmCariTarihB2B ?? CurrentCompany.frmCariTarih,
                        };
            return View(model);
        }

        #endregion

        #region Mutabakat


        [B2BAuthorize(AccountType.Supplier | AccountType.Customer, Privilege.FATURA)]
        public ActionResult Reconsilation()
        {
        
            var reconsilations = new ReconsilationModel
            {
                Reconsilations =
                                Db.carMtbkt
                                .Select(x => new ReconsilationModel.Reconsilation
                                {
                                    BillAmount = x.mtbktAdet,
                                    EndDate = x.mtbktBitisTarih,
                                    TotalAmount = x.mtbktTutar,
                                    StartDate = x.mtbktBaslangicTarih,
                                    ReconsilationId = x.mtbktID
                                }).OrderByDescending(x => x.EndDate).ToList(),

                UnConfirmedReconsilations = new ReconsilationModel.Reconsilation
                {
                    BillAmount =
                          (from fat in Db.fat
                           let a = Db.carMtbkt.Max(x => x.mtbktBitisTarih)
                           let b = CurrentCompany.frmCariTarih
                           where fat.eFirma == CurrentCompany.frmID
                           where fat.eTarih >= a && fat.eTarih < b
                           select fat).Count(),
                    TotalAmount =
                           (from fatAyr in Db.fatAyr
                            join fat in Db.fat on fatAyr.ehID equals fat.eID
                            let a = Db.carMtbkt.Max(x => x.mtbktBitisTarih)
                            let b = CurrentCompany.frmCariTarih
                            where fat.eFirma == CurrentCompany.frmID
                            where fat.eTarih >= a && fat.eTarih < b
                            select (decimal?)fatAyr.ehTutar).Sum()
                }
            };

            return View(reconsilations);
        }

        [B2BAuthorize(AccountType.Supplier | AccountType.Customer, Privilege.FATURA)]
        public ActionResult ReconsilationDetails(int? id)
        {
            if (id != null)
            {
                var mutabakat = Db.carMtbkt.Single(x => x.mtbktID == id);

                var model = new ReconsilationDetailsModel{
                Reconsilate =true,
                StartDate = mutabakat.mtbktBaslangicTarih,
                EndDate = mutabakat.mtbktBitisTarih,
                Invoices = 
                   ( from fat in Db.fat
                    join frm in Db.frm on fat.eFirma equals frm.frmID
                    join sifTip in Db.sifTip on fat.eTip equals sifTip.hrktTipID
                    join sipNeden in Db.sipNeden on fat.Neden equals sipNeden.nedenID
                    join posMagaza in Db.posMagaza on fat.eMekan equals posMagaza.mekanID
                    join firmaMekan in Db.frm on fat.eFirmaMkn equals firmaMekan.frmID
                   /* Only Invoices for siftip */
                    where sifTip.hrktSIF == 2
                    where frm.frmID == CurrentAccount.frm.frmID
                    where fat.eTarih>=mutabakat.mtbktBaslangicTarih &&                                                   fat.eTarih<mutabakat.mtbktBitisTarih
                    orderby fat.eTarih descending, fat.eID descending
                    select new ReconsilationDetailsModel.Invoice
                    {
                        Id = fat.eID,
                        Tarih = fat.eTarih,
                        EvrakNo = fat.eNo,
                        HareketTipi = sifTip.hrktTipAd,
                        Durum = (ReconsilationDetailsModel.InvoiceStatus)fat.eDurum,
                        VadeTarihi = fat.eTarihV,
                        EvrakNot = fat.eNot,
                        KDVHaricToplam = fat.fatAyr.Sum(x => x.ehTutar),
                        ToplamIndirim = fat.fatAyr.Sum(x => x.ehIndirim),
                        HareketGrubu = sipNeden.nedenAd,
                        SevkAdresi = frm.frmTip == 1 ? (fat.eFirmaMkn == 0 ? "" : firmaMekan.frmAd) : posMagaza.mekanAd
                    }).ToList()
                };
                return View(model);
            }
            else
            {
                var mutabakat = Db.carMtbkt.Where(x => x.mtbktFrmID == CurrentCompany.frmID)
                                           .OrderByDescending(x => x.mtbktBitisTarih)
                                           .First();

                var model = new ReconsilationDetailsModel
                {
                    Reconsilate = false,
                    EndDate = mutabakat.mtbktBitisTarih,
                    Invoices = (
                        from fat in Db.fat
                        join frm in Db.frm on fat.eFirma equals frm.frmID
                        join sifTip in Db.sifTip on fat.eTip equals sifTip.hrktTipID
                        join sipNeden in Db.sipNeden on fat.Neden equals sipNeden.nedenID
                        join posMagaza in Db.posMagaza on fat.eMekan equals posMagaza.mekanID
                        join firmaMekan in Db.frm on fat.eFirmaMkn equals firmaMekan.frmID
                        /* Only Invoices for siftip */
                        where sifTip.hrktSIF == 2
                        where frm.frmID == CurrentAccount.frm.frmID
                        where fat.eTarih > mutabakat.mtbktBitisTarih
                        orderby fat.eTarih descending, fat.eID descending
                        select new ReconsilationDetailsModel.Invoice
                        {
                            Id = fat.eID,
                            Tarih = fat.eTarih,
                            EvrakNo = fat.eNo,
                            HareketTipi = sifTip.hrktTipAd,
                            Durum = (ReconsilationDetailsModel.InvoiceStatus)fat.eDurum,
                            VadeTarihi = fat.eTarihV,
                            EvrakNot = fat.eNot,
                            KDVHaricToplam = fat.fatAyr.Sum(x => x.ehTutar),
                            ToplamIndirim = fat.fatAyr.Sum(x => x.ehIndirim),
                            HareketGrubu = sipNeden.nedenAd,
                            SevkAdresi = frm.frmTip == 1 ? (fat.eFirmaMkn == 0 ? "" : firmaMekan.frmAd) : posMagaza.mekanAd
                        }).ToList()
                };
                return View(model);
            }

      }
         [B2BAuthorize(AccountType.Supplier | AccountType.Customer, Privilege.FATURA)]
       public ActionResult ConfirmReconsilation(DateTime startdate,int count,decimal total)
         {
             var newReconsilation = new carMtbkt
                                        {
                                           mtbktBaslangicTarih = startdate,
                                           mtbktBitisTarih = DateTime.Now,

Backup/Derinsis.B2B/Views/Accounting/Activities.cshtml
@using System.Globalization
@model DerinSIS.B2B.ViewModels.AccountActivitiesModel
@{
    ViewBag.Title = "Hesap Hareketleri";
    ViewBag.SubTitle = "Muhasebe";
}


<form method="GET">
    @{ Html.RenderPartial("DocumentDateFilter", Model.DateFilter); }
</form>


<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th>Tarih</th>
            <th>Hareket Tipi</th>
            <th>Evrak No</th>
            <th>Vade Tarihi</th>
            <th class="right-aligned">Borc</th>
            <th class="right-aligned">Alacak</th>
            <th class="right-aligned">Bakiye</th>    
        </tr>
    </thead>
    <tbody>
        @{
            var sonBakiye = Model.DevredenBakiye;
        }

        <tr class="activity-trans">
            <td colspan="2"></td>
            <td colspan="3">Devreden Bakiye</td>
            <td class="right-aligned">@(sonBakiye < 0 ? sonBakiye.ToMoneyFormat() : "")</td>
            <td class="right-aligned">@(sonBakiye >= 0 ? sonBakiye.ToMoneyFormat() : "")</td>
            <td class="right-aligned">@Model.DevredenBakiye.ToMoneyFormat()</td>
        </tr>
        
        @if (Model.Activities.Any())
        {
            var currentDate = Model.DateFilter.Begin.Value;
            var endDate = Model.DateFilter.End.Value;

            while (currentDate <= endDate)
            {
                var dayRecords = Model.Activities.Where(x => x.Tarih == currentDate);
                foreach (var activity in dayRecords)
                {
                    
                    <tr>
                        <td>
                            @if (activity.IlgiliFaturaId.HasValue)
                            {
                                <a href="@Url.Action("InvoiceDetail", "Accounting", new { id = activity.IlgiliFaturaId })" class="btn btn-info related-invoice-link" 
                                   data-title="İlişkili Faturaya Git" data-content="Cari hareketin faturasını görmek için tıklayınız.<br /><br /><em>Fatura #@activity.IlgiliFaturaNo</em>">
                                    <i class="icon-list-alt icon-white"></i>
                                </a>
                            }
                        </td>
                        <td>@activity.Tarih.ToShortDateString()</td>
                        <td>@activity.HareketTipi</td>
                        <td>
                            @if (!string.IsNullOrWhiteSpace(activity.IlgiliFaturaNo))
                            {
                                @activity.EvrakNo
                            }
                        </td>
                        <td>@activity.VadeTarihi.ToShortDateString()</td>
                        <td class="right-aligned">@(activity.Borc == null ? "--" : activity.Borc.Value.ToMoneyFormat())</td>
                        <td class="right-aligned">@(activity.Alacak == null ? "--" : activity.Alacak.Value.ToMoneyFormat())</td>
                        <td class="right-aligned">@activity.Bakiye.Value.ToMoneyFormat()</td>
                    </tr>
            
                    sonBakiye = activity.Bakiye.Value;
                }
                
                if(currentDate.IsLastDayOfMonth() && Model.Activities.Any(x => x.Tarih.Year == currentDate.Year && x.Tarih.Month == currentDate.Month))
                {
                    <tr class="activity-trans">
                        <td colspan="2"></td>
                        <td colspan="3">@currentDate.ToString("MMMM", new CultureInfo("tr-TR")) Bakiyesi</td>
                        <td class="right-aligned">@(sonBakiye < 0 ? sonBakiye.ToMoneyFormat() : "")</td>
                        <td class="right-aligned">@(sonBakiye >= 0 ? sonBakiye.ToMoneyFormat() : "")</td>
                        <td class="right-aligned">@sonBakiye.ToMoneyFormat()</td>
                    </tr>
                }

                if(currentDate == Model.MutabakatTarihi)
                {
                    <tr class="activity-mutabakat">
                        <td></td>
                        <td>@Model.MutabakatTarihi.ToShortDateString()</td>
                        <td colspan="3">Mutabakat Sonu</td>
                        <td class="right-aligned">@(sonBakiye < 0 ? sonBakiye.ToMoneyFormat() : "")</td>
                        <td class="right-aligned">@(sonBakiye >= 0 ? sonBakiye.ToMoneyFormat() : "")</td>
                        <td class="right-aligned">@sonBakiye.ToMoneyFormat()</td>
                    </tr>
                }

                currentDate = currentDate.AddDays(1);
            }
            
            <tr class="activity-trans">
                <td colspan="2"></td>
                <td colspan="3">Devreden Bakiye</td>
                <td class="right-aligned">@(sonBakiye < 0 ? sonBakiye.ToMoneyFormat() : "")</td>
                <td class="right-aligned">@(sonBakiye >= 0 ? sonBakiye.ToMoneyFormat() : "")</td>
                <td class="right-aligned">@sonBakiye.ToMoneyFormat()</td>
            </tr>
        }
           
    </tbody>
</table>



@section javascripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $('.related-invoice-link').popover();
        });
    </script>
}

Backup/Derinsis.B2B/Views/Accounting/Index.cshtml
@model DerinSIS.B2B.ViewModels.AccountingDashboardModel
@{
    ViewBag.Title = "Muhasebe";
}

<div class="row">
    
    <div class="span5">
        <div class="block block-float">
            <div class="block-header">
                <h2>MUTABAKAT</h2>
            </div>
            <div class="block-content">                
                <table class="table">
                    @if(Model.SistemMutabakatTarihi == Model.FirmaMutabakatTarihi)
                    {
                        <tr>
                            <td>
                                <span class="label label-success label-mutabakat">OK</span>
                            </td>
                            <td>Son Mutabakat Tarihi:</td>
                            <td class="right-aligned">
                                <strong>@Model.SistemMutabakatTarihi.ToDateString()</strong>
                            </td>
                        </tr>       
                    }
                    else if (Model.FirmaMutabakatTarihi > Model.SistemMutabakatTarihi)
                    {
                        <tr>
                            <td>
                                <span class="label label-success label-mutabakat">OK</span>
                            </td>
                            <td>Son Mutabakat Tarihi:</td>
                            <td class="right-aligned">
                                <strong>@Model.SistemMutabakatTarihi.ToDateString()</strong>
                            </td>
                        </tr>   
                    }
                    else
                    {
                        <tr>
                            <td></td>
                            <td>
                                <span class="label label-important label-mutabakat">
                                    MUTABAKAT İÇİN ONAYINIZ BEKLENİYOR    
                                </span>
                                
                            </td>
                            <td class="right-aligned">
                                <a href="@Url.Action("Mutabakat")" class="btn btn-warning">Onay Ver</a>
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>Son Mutabakat Tarihi:</td>
                            <td class="right-aligned">
                                <strong>@Model.FirmaMutabakatTarihi.ToDateString()</strong>
                            </td>
                        </tr> 
                        <tr>
                            <td></td>
                            <td>Onay Bekleyen Tarih:</td>
                            <td class="right-aligned">
                                <strong>@Model.SistemMutabakatTarihi.ToDateString()</strong>
                            </td>
                        </tr>   
                    }
                </table>
            </div>
        </div>
        
        <hr />

        <div class="block block-float">
            <div class="block-header">
                <h2>ÖDENMEMİŞ FATURALAR</h2>
            </div>
            
            <div class="block-content">
                @if (Model.OdenmemisFaturalar.Any())
                {
                    <table class="table table-striped table-condensed">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Evrak No</th>
                                <th>Fatura Tarihi</th>
                                <th>Vade Tarihi</th>
                                <th class="right-aligned">Kalan Tutar</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var fatura in Model.OdenmemisFaturalar)
                            {
                                <tr>
                                    <td>
                                        <a href="@Url.Action("InvoiceDetail", "Accounting", new { id = fatura.Id })" class="btn btn-info btn-mini">
                                            <i class="icon-search icon-white"></i>
                                        </a>
                                    </td>
                                    <td>@fatura.EvrakNo</td>
                                    <td>@fatura.FaturaTarihi.ToShortDateString()</td>
                                    <td>@fatura.VadeTarihi.ToShortDateString()</td>
                                    <td class="right-aligned">@fatura.KalanTutar.ToMoneyFormat()</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <em>Ödenmemiş Fatura Bulunmamaktadır.</em>
                }
            </div>
        </div>
    </div>

    <div class="span4">
        <div class="block block-float">
            <div class="block-header">
                <h2>BAKİYE BİLGİLERİ</h2>
            </div>
            
            <div class="block-content">
                <table class="table table-striped">
                    <tr>
                        <td>Borç</td>
                        <td class="right-aligned">@Model.Borc.ToMoneyFormat()</td>
                    </tr>
                    <tr>
                        <td>Alacak</td>
                        <td class="right-aligned">- @Model.Alacak.ToMoneyFormat()</td>
                    </tr>
                    <tr>
                        <td>Bakiye</td>
                        <td class="right-aligned">@Model.Bakiye.ToMoneyFormat(true)</td>
                    </tr>
                </table>
            </div>
        </div>

        <hr />
        
        <div class="block block-float">
            <div class="block-header">
                <h2>BANKA HESAP BİLGİLERİ</h2>
            </div>
            
            <div class="block-content">
                @if (Model.BankaHesapBilgileri.Any())
                {
                    <table class="table table-striped">
                        @foreach (var bankaHesapBilgisi in Model.BankaHesapBilgileri)
                        {
                            <tr>
                                <td>
                                    @bankaHesapBilgisi.Banka - @bankaHesapBilgisi.Sube <br />
                                    @bankaHesapBilgisi.HesapNo
                                </td>
                            </tr>
                        }
                    </table>
                }
                else
                {
                    <em>Kayıtlı Banka Hesap Bilgisi Bulunmamaktadır.</em>
                }
            </div>
        </div>
    </div>
</div>

Backup/Derinsis.B2B/Views/Accounting/Invoices.cshtml
@using DerinSIS.B2B.ViewModels
@model InvoicesModel
@{
    ViewBag.Title = "Faturalar";
    ViewBag.SubTitle = "Muhasebe";
}


<form method="GET">
    <input type="hidden" name="productFilter" value="@Model.ProductFilterId"/>

    @if(Model.ProductFilterId.HasValue)
    {
        <div class="alert alert-info">
            <button type="button" class="a btn btn-danger btn-small remove-product-filter"><i class="icon-remove icon-white"></i></button>
            <span class="label label-important">ÜRÜN FİLTRESİ</span>
            <strong>@Model.ProductFilterLabel</strong>
        </div>
        
        <script type="text/javascript">
            $(document).ready(function () {
                $('.remove-product-filter').click(function () {
                    var t = $(this);

                    // remove value from input productFilter
                    $('input[name=productFilter]').val('');

                    // submit form
                    t.closest('form').submit();
                });
            });
        </script>
    }
    
    @{ Html.RenderPartial("DocumentDateFilter", Model.DateFilter); }
    @{ Html.RenderPartial("DocumentTypeFilter", Model); }
</form>


@if (Model.Invoices.Any())
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th>Tarih</th>
                <th>Evrak No</th>
                <th>Hareket Tipi</th>
                <th>Vade Tarihi</th>
                
                @if(Model.GosterimSecenekleri.EvrakNotuGosterilsinMi)
                {
                    <th>Evrak Notları</th>    
                }
                
                <th class="right-aligned">KDV Hariç</th>
                <th class="right-aligned">Toplam İndirim</th>
                <th class="right-aligned">KDV Hariç Net</th>
                <th>Hareket Grubu</th>    
                <th>Sevk Adresi</th>        
            </tr>
        </thead>
        <tbody>
            @foreach (var invoice in Model.Invoices)
            {
                <tr>
                    <td>
                        <a href="@Url.Action("InvoiceDetail", new { id = invoice.Id })" class="btn btn-info" data-toggle="button">
                            <i class="icon-search icon-white"></i>
                        </a>
                    </td>
                    <td>
                        @if (invoice.Durum == InvoicesModel.InvoiceStatus.IPTAL)
                        {
                            <span class='label label-important'>İPTAL</span>
                        }
                    </td>
                    <th>@invoice.Tarih.ToShortDateString()</th>
                    <td>@invoice.EvrakNo</td>
                    <td>@invoice.HareketTipi</td>
                    <td>@invoice.VadeTarihi.ToShortDateString()</td>
                    
                    @if (Model.GosterimSecenekleri.EvrakNotuGosterilsinMi)
                    {
                        <td>@invoice.EvrakNot</td>    
                    }
                    
                    <td class="right-aligned no-wrap">@invoice.KDVHaricToplam.ToMoneyFormat()</td>
                    <td class="right-aligned no-wrap">@invoice.ToplamIndirim.ToMoneyFormat()</td>
                    <td class="right-aligned no-wrap">@invoice.KDVHaricNet.ToMoneyFormat()</td>
                    <td>@invoice.HareketGrubu</td>
                    <td>@invoice.SevkAdresi</td>    
                </tr>
            }
        </tbody>
    </table>

}
else
{
        <div class="alert alert-error">
            <h4 class="alert-heading">Kayıt Bulunamadı!</h4>
            Aradığınız tarihler için fatura kaydı bulunamadı.
            Lütfen arama başlangıç ve bitiş tarihlerini değiştirip tekrar deneyin.
        </div>
}

Backup/Derinsis.B2B/Views/Accounting/Reconsilation.cshtml
@model DerinSIS.B2B.ViewModels.ReconsilationModel
@{
    ViewBag.Title = "Mutabakat";
    ViewBag.SubTitle = "Muhasebe";
}

<div class="row">
    <div class="span9">
       
                <table class="table">
                    <thead>
                        <th></th>
                        <th>Başlangıç</th>
                        <th>Bitiş</th>
                        <th>Adet</th>
                        <th>Tutar</th>
                    </thead>
                    <tbody>
                        @if(Model.UnConfirmedReconsilations.BillAmount!=0)
                              {
                                  <tr>
                                      <td>
                                          <a href="@Url.Action("ReconsilationDetails", new { id =Model.UnConfirmedReconsilations.ReconsilationId })" class="btn btn-warning"><i class="icon-edit icon-white"></i></a>
                                      </td>
                                      <td style="padding-left: 20px;">
                                          -
                                      </td>
                                      <td style="padding-left: 20px;">
                                          -
                                      </td>
                                      <td style="padding-left: 10px;">
                                          @Model.UnConfirmedReconsilations.BillAmount
                                      </td>
                                      <td>
                                          @Model.UnConfirmedReconsilations.TotalAmount
                                      </td>
                                  </tr>
                              }
                        
                        @foreach (var item in Model.Reconsilations)
                        {
                            <tr>
                                <td>
                                    <a href="@Url.Action("ReconsilationDetails", new { id=item.ReconsilationId})"                           class="btn btn-success"><i class="icon-edit icon-white"></i></a>
                                </td>
                                <td>
                                    @item.StartDate.ToShortDateString()
                                </td>
                                <td>
                                    @item.EndDate.ToShortDateString()
                                </td>
                                <td style="padding-left: 10px;">
                                    @item.BillAmount
                                </td>
                                <td>
                                    @item.TotalAmount
                                </td>
                            </tr>
                        } 
                    </tbody>
                 
                </table>
            </div>
        
</div>

Backup/Derinsis.B2B/Views/Accounting/_AccountingLayout.cshtml
@using DerinSIS.B2B.Helpers.Html
@{
    Layout = "~/Views/Shared/_ContentLayout.cshtml";
}


@section sidebar
{
    <div class="well">
        <ul class="nav nav-list">
            
            <li class="nav-header">Muhasebe</li>
            @Url.SidebarLink("Özet", "Index", "Accounting", "home")
            @Url.SidebarLink("Hesap Hareketleri", "Activities", "Accounting", "play")
            @Url.SidebarLink("Faturalar", "Invoices", "Accounting", "th-list")
            @Url.SidebarLink("Mutabakat", "Reconsilation", "Accounting", "file")
            <li class="nav-header">Raporlar</li> 
            @Url.SidebarLink("Mağaza Bazlı Satış", "salesPerStore", "Accounting", "file")
        </ul>
    </div>
}


@RenderBody()


@section javascripts
{
    @RenderSection("javascripts", required: false)
}